# Project: secrets-reader
# File: azure-pipelines.yml
# Ref:
# https://gavincampbell.dev/post/azure-devops-retrieving-secrets/
#


trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: VariableGroupContainingSecretVar

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo "pipelineScopedSecretVar = $(pipelineScopedSecretVar)" >> $PIPELINE_WORKSPACE/secrets.txt
      echo "secretVarInVariableGroup = $(secretVarInVariableGroup)" >> $PIPELINE_WORKSPACE/secrets.txt
      env

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/secrets.txt'
    artifact: 'Secrets'
    publishLocation: 'pipeline'
